# Message for requesting game actions
Header header

# which game
int8 game

# which command
int8 command

# which level to play
int8 level

# Games
int8 STORYTELLING = 0
int8 ROCKET_BARRIER = 1
int8 GALACTIC_TRAVELER = 2
int8 SPACESHIP_TIDYUP = 3
int8 ALIEN_CODES = 4
int8 HOUSE_PERSPECTIVE_TAKING = 5
int8 TRAIN_SEQUENCING = 6
# add new games here..

# Commands
int8 START = 0
int8 CONTINUE = 1
int8 PAUSE = 2
int8 END = 3
int8 WAIT_FOR_RESPONSE = 4
int8 SKIP_RESPONSE = 5
int8 PLAY_TUTORIAL = 6
